// Variables--- ozgaruvchilar 3 turga bulinadi ==> var, let, const

// const a = 'olma';

// const a = 'gilos'
// a = 'anor';
// console.log(a);



// DATA TYPES==> Malumot turlari ==> 8ta turi mavjud
// 2ga bulinadi--- 
// 1 Primitive -----> string, number, null, boolean, bigInt, symbol, undifined.
// 2 Nan-primitive---> object.====> 3ga bulinadi ----> array, object, function.
// ===============================================================================
// let a = 'Mohichehra'
// let str = `hello ${a} Komila`

// console.log( str);

// ==============================================================================
// number

// let num = 23;
// let number = 4;
// console.log(number - num);

// ====================================================================================
// Null

// let a = 0;
 

// console.log( a + 1);

// ====================================================================================
// undifined

// let a;
// console.log(typeof a);


// ====================================================================================
// Boolean
// true/false
// ====================================================================================
// BigInt

// let big = 5467898765456789n
//  console.log(typeof big);

// ====================================================================================
// Symbol

// let a = Symbol('hello')
// let b = Symbol('hello')

// console.log(a == b);

// ====================================================================================
// Object--- 
// array=== ['hello', 12, 'age'] === index orqali chaqiriladi.
// let arr = ['salom', 120, 'yosh']
// console.log(typeof arr);

// object === {name: Salim, age:25, status: doctor} === nuqtadan kn keywordni quyish orqali qiymqtni bittalab chaqirish mumkin.

// let obj = {name: 'Salim', age:25, status: 'doctor'}

// console.log(obj.name);


// function== ()=>{} --> arrow function
// function name() {}